ui5-community/ui5-ecosystem-showcase

- README.md
- package.json
- packages/ui5-app/package.json
- packages/ui5-middleware-cfdestination/package.json
- packages/ui5-middleware-iasync/package.json
- packages/ui5-middleware-livereload/package.json
- packages/ui5-middleware-livetranspile/package.json
- packages/ui5-middleware-servestatic/package.json
- packages/ui5-middleware-simpleproxy/package.json
- packages/ui5-task-transpile/package.json
- yarn.lock
One interesting piece is that the babel-cli dependency made the startup of the `ui5 serve` or `ui5 build `tremendously slow. I removed the dependency from the `ui5-task-transpile` now as it is even not needed.
I fixed a small visual issue in the documentation after adding the `ui5-task-zipper` to have a proper ASCII tree visualization... :-)
Upgraded all dependencies to the latest and greatest.
> Performance fixes, docu fixes and dependency upgrades

- packages/ui5-app/ui5.yaml
- packages/ui5-app/webapp/controller/App.controller.js
- packages/ui5-task-transpile/README.md
- packages/ui5-task-transpile/lib/transpile.js
- packages/ui5-task-transpile/package.json
Hello,
sometimes I want to remove all console-statements from an application, before it is deployed. First I wanted to write a new task, but then I found out that there's a babel plugin. So I've extended `ui5-task-transpile`.
Happy to hear your feedback.
Best regards,
Lukas
> removing console statements

- packages/ui5-middleware-simpleproxy/README.md
- packages/ui5-middleware-simpleproxy/lib/proxy.js
Fix the issue when using HTTPS and self-signed certificates giving the option for developers to turn it on/off as required.
```bash
Error: unable to verify the first certificate
at TLSSocket.onConnectSecure (_tls_wrap.js:1321:34)
at TLSSocket.emit (events.js:210:5)
at TLSSocket._finishInit (_tls_wrap.js:794:8)
at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:608:12)
```
The solution is based on the express-http-proxy documentation: https://github.com/villadora/express-http-proxy#q-how-to-ignore-self-signed-certificates-
This blog has a workaround for it, but doesn't fix the issue in the proxy: https://blogs.sap.com/2019/11/29/how-to-get-your-preferred-javascript-ide-ready-for-sapui5-development
> Ignore self-signed certificates

- packages/ui5-middleware-cfdestination/package.json
- packages/ui5-middleware-iasync/package.json
- packages/ui5-middleware-index/package.json
- packages/ui5-middleware-livereload/package.json
- packages/ui5-middleware-livetranspile/package.json
- packages/ui5-middleware-servestatic/package.json
- packages/ui5-middleware-simpleproxy/package.json
- packages/ui5-task-transpile/package.json
- packages/ui5-task-zipper/package.json
Enable UI5 Tooling to skip analysis of irrelevant packages. This speeds
up dependency processing and reduces the likelyhood of "JavaScript heap
out of memory" issues.
> package.json: Ignore all non-ui5 dependencies

- packages/ui5-middleware-servestatic/README.md
- packages/ui5-middleware-servestatic/lib/serveStatic.js
- packages/ui5-middleware-servestatic/package.json
Hi @petermuessig,
I added a new config option called `pathIsEnvVar`. If this option is set to `true` it is expected that the `rootPath` variable contains an environment variable contained in a `.env` file.
This makes collaberation in a ui5 repository easier as the `ui5.yaml` does not have to be adjusted by every user locally - not all users store their static resources in the same path.
Regards
Ludwig
> New option in ui5-middleware-servestatic to use paths from .env file

- packages/ui5-middleware-cfdestination/lib/cfdestination.js
Local routes break the middleware because the "webapp" folder doesn't exist.
The webapp is already served by the UI5 tooling itself, so this route isn't needed anylonger.
> Ignore local routes

- packages/ui5-middleware-simpleproxy/README.md
- packages/ui5-middleware-simpleproxy/lib/proxy.js
- packages/ui5-middleware-simpleproxy/package.json
This pull request provides support in ui5-middleware-simpleproxy for specifying the `baseUri` and `strictSSL` configuration via environment variable or `.env` file. This addresses issue #174 for this package.
Also:
- Removes repetitive existence-checked access of `options.configuration`
- Adds a existence check on access of `options.configuration.debug` that is now required because it is possible to run without a configuration section
> Support for environment variables and .env for baseUri and strictSSL

- packages/ui5-middleware-livereload/README.md
- packages/ui5-middleware-livereload/lib/livereload.js
- packages/ui5-middleware-livereload/package.json
- yarn.lock
Setting automatically an open port in case the `option.configuration.port` is not supplied. The free port selection is made by [portfinder](https://www.npmjs.com/package/portfinder), it scans the ports from _35729_ toward _65535_.
> Automatically set a non-taken port for livereload server

- packages/ui5-middleware-cfdestination/lib/cfdestination.js
Hey everyone,
as discussed in #185, the destinations property is now defaulted to an empty array instead of throwing a technical error if the property is not present.
This is a prerequisite for more enhancements I would like to provide, which are discussed in the issue.
If you have any enhancements, please comment 👍 
BR Robert
> Empty destinations enhancement

- packages/ui5-app/.env
- packages/ui5-app/package.json
- packages/ui5-app/ui5.yaml
- packages/ui5-app/webapp/controller/App.controller.js
- packages/ui5-task-stringreplacer/CHANGELOG.md
- packages/ui5-task-stringreplacer/README.md
- packages/ui5-task-stringreplacer/lib/stringreplacer.js
- packages/ui5-task-stringreplacer/package.json
- packages/ui5-task-stringreplacer/ui5.yaml
Hello @petermuessig  and @vobu ,
In one of my project we had below requirements
- Replacing API URLs based on different deployment environment.
- We had few applications links which can be opened from our UI5 application. These links were pointing to different URLs in each deployment environment.
- Also we wanted to manage copyright text and other few dynamic texts based on different builds.
So earlier we were using grunt-replace for all these requirement. Since we are migrating our applications to UI5 tools now, thought of creating a custom UI5 task which will fix all our requirements.
Screenshots from sample code:
Source code:
Managing string placeholders in .yaml
dbg file inside dist
Currently I am handling different environment deployments using multiple .yaml files. But it can be …
> feat: new custom task - stringsreplacer

- README.md
Current README.md file link for string replacer npm package is not correct. Updated it with correct URL.
> fix: fixed minor typo with npm package link

- packages/ui5-middleware-simpleproxy/lib/proxy.js
When removing the secure flag from the cookie one semicolon must remain.
Otherwise cookie attributes might be merged into values, leading to invalid cookies.
Before this change both semicolons before and after the secure flag were removed.
This change makes sure one of them remains.
Fixes: #236
> Keeps cookie structure after removing secure flag while proxying

- packages/ui5-middleware-livereload/lib/livereload.js
Today I updated the livereload middleware for my project and the livereload-server was logging verbosely although I disabled that via configuration.
It took some debugging for me to detect the issue. 
`if (options.configuration && options.configuration.debug) {` is only true if debug is configured as true. This causes that the configured `false` will never be written in let debug. Simple workaround for that is defaulting the debug variable to false (I anyway don´t see the point for enabling it).
> fix: default to debug false

- packages/ui5-middleware-livetranspile/README.md
- packages/ui5-task-transpile/README.md
I added documentation to `ui5-task-transpile` and `ui5-middleware-livetranspile` that describes how to add more configuration options to babel. The configuration for both packages is identical and I added the detailed documentation to `ui5-task-transpile` only. The `ui5-middleware-livetranspile` references to that documentation.
Closes: #246
> Add documentation for extended babel configuration

- packages/ui5-app/package.json
- packages/ui5-app/ui5-custom-babel.yaml
- packages/ui5-app/ui5.yaml
- packages/ui5-app/webapp/includes/iWillBeTranspiled.js
- packages/ui5-middleware-livetranspile/README.md
- packages/ui5-middleware-livetranspile/lib/livetranspile.js
- packages/ui5-middleware-livetranspile/package.json
- packages/ui5-task-transpile/README.md
- packages/ui5-task-transpile/lib/transpile.js
- yarn.lock
This PR implements the configuration option `babelConfig` in both `ui5-task-transpile` and `ui5-middleware-livetranspile`.
If set, the option `babelConfig` makes sure both packages will discard their default babel configuration and use whatever is given in `babelConfig`. Like this the user has full control over how exactly the code is transpiled.
The documentation of both packages has been enhanced accordingly.
Also the `ui5-app` has been given a sample babel configuration though I'm not sure if that's really necessary.
> Enable overriding babel configuration

- packages/ui5-app/ui5.yaml
- packages/ui5-middleware-simpleproxy/README.md
- packages/ui5-middleware-simpleproxy/lib/proxy.js
Additional configuration option "limit" in `ui5.yaml`:
```yaml
- name: ui5-middleware-simpleproxy
mountPath: /ui5
afterMiddleware: compression
configuration:
baseUri: "https://sapui5.hana.ondemand.com/"
limit: "5mb"
```
Fixes: https://github.com/petermuessig/ui5-ecosystem-showcase/issues/293
> feat(simpleproxy): allow to increase payload limit

- packages/ui5-app/ui5.yaml
- packages/ui5-middleware-simpleproxy/README.md
- packages/ui5-middleware-simpleproxy/lib/proxy.js
```yaml
server:
customMiddleware:
- name: ui5-middleware-simpleproxy
afterMiddleware: compression
mountPath: /odata
configuration:
baseUri: "http://services.odata.org"
removeETag: true
```
Fixes: https://github.com/petermuessig/ui5-ecosystem-showcase/issues/292
> feat(simpleproxy) allow to remove the ETag from the response

- packages/ui5-middleware-livetranspile/lib/livetranspile.js
- packages/ui5-task-transpile/lib/transpile.js
- packages/ui5-task-transpile/ui5.yaml
This PR affects ui5-middleware-livetranspile as well as ui5-task-transpile.
It allows for Babel consumption of different file types other than JS.
See #359 
By default only JS files are considered. The pattern for file lookup can be configured in `ui5.yaml` via attribute `filePattern`, e.g.:  ```filePattern: ".{js,ts}"```
ui5-task-transpile will emit the source files for transpilation, e.g. Component.ts, in addition to the transpiled JS files.
Can be worked around by adding rimraf to the build script in package.json:
```
"scripts": {
"serve": "ui5 serve",
"build": "ui5 build && rimraf dist/**/*.ts"
}
```
Are there better ways to make this happen by means of the UI5 tooling API?
> feat: allow for file patterns as JS input source

- packages/ui5-middleware-cfdestination/lib/cfdestination.js
Ignore routes that point to the HTML5 app repo like:
```
{
"source": "^(.*)",
"target": "$1",
"authenticationType": "xsuaa",
"service": "html5-apps-repo-rt"
}
```
> Adding a second filter criteria

- packages/ui5-app/package.json
- packages/ui5-app/webapp/test/e2e-wdi5/pages/Main.js
- packages/ui5-app/webapp/test/e2e-wdi5/pages/Page.js
- packages/ui5-app/webapp/test/e2e-wdi5/tests.test.js
- yarn.lock
`wdi5` now works with both ui5-tooling- and other web-servers, respecting a default directory index file - 
thus "index" is moved to `wdi5` config time and doesn't have to be manually called in tests any more.
fixes #443
> tests: adjust to updated wdi5 (fixes #443)

- packages/ui5-middleware-livereload/lib/livereload.js
if no configuration at all is specified, the middleware used to crash `ui5 serve`.
(we'll optional-chain such cases once node 14 lts is more widely adopted)
> fix: non-specified exclusions crash the server

- packages/ui5-middleware-cfdestination/README.md
- packages/ui5-middleware-cfdestination/lib/cfdestination.js
Add auth support. 
The user can pass the authenticationMethod via the options 
and the authentication method defined in the routes is respected and used
> Add auth to routes

- package.json
- packages/ui5-app/ui5.yaml
- packages/ui5-app/webapp/proxy/local/hello.txt
- packages/ui5-middleware-simpleproxy/README.md
- packages/ui5-middleware-simpleproxy/lib/proxy.js
- packages/ui5-middleware-simpleproxy/package.json
With this change I enable the simpleproxy to use exclude patterns in glob syntax to define which paths should not be proxied. This is quite helpful when mixing proxy and local resources.
> feature(simpleproxy): adding excludePatterns for proxy requests

- packages/ui5-task-flatten-library/lib/flatten-library.js
The current task implementation basically re-includes such resources in
the build result.
> fix(flatten-library): Ignore resources tagged as 'omit from build result'

- packages/ui5-middleware-cfdestination/lib/cfdestination.js
- packages/ui5-middleware-cfdestination/package.json
Fixing reported issue #503 and update app router to latest version (`9.3.0`). Based on the global `authenticationType` setting, either the route's `authenticationMethod` is being used or set to `none`.
> [FIX] Auth Routes Config

- packages/ui5-middleware-livereload/README.md
- packages/ui5-middleware-livereload/lib/livereload.js
- packages/ui5-middleware-livereload/package.json
> fix(livereload): support HTTP/2 --h2 option

- packages/ui5-middleware-simpleproxy/lib/proxy.js
When adding uri parameters to the proxy request the "req.query" parameter object contains the parameters unescaped and the finaly build uri of them will also be unescaped
> missing encoding of uri parameters

- packages/ui5-middleware-simpleproxy/lib/proxy.js
- yarn.lock
req.path and req.url are already fully encoded so we only need to encode the url parameters to prevent double encoding
closes : https://github.com/ui5-community/ui5-ecosystem-showcase/issues/529
> fix: encoding of full url

- packages/ui5-middleware-simpleproxy/README.md
If the sap-client number starts with zero (e.g. 001) and it got configured here without quotes, then the proxy will try to connect to sap-client 1 instead of 001.
Furthermore, the proxy log will not point the developer to this wrong sap-client 1. It is quite hard to figure out the wrong configuration.
Hence, we shall give a hint in this documentation, that the client shall be entered always with quotes.
> sap-client shall be configured with quotes

- packages/ui5-tooling-modules/lib/util.js
Fixed error in ui5-tooling-modules\lib\util.js which made the build task fail completly when using ui5-tooling-modules
> Fixed error in ui5-tooling-modules

- packages/ui5-middleware-simpleproxy/README.md
- packages/ui5-middleware-simpleproxy/lib/proxy.js
The skipcache flag is introduced to remove the ~<GUID>~ cache when serving the embedded FLP
launchpad and it matches an exclude pattern. Also fixed a bug on the excludepattern when using an
array with more than one entry as it was always returning true.
> feat(SimpleProxy):  added a feature to skip the server cache 

- packages/ui5-app-module/Chart.js
- packages/ui5-app-module/ChartRecord.js
- packages/ui5-app-module/package.json
- packages/ui5-app/package.json
- packages/ui5-app/ui5-min.yaml
- packages/ui5-app/ui5.yaml
- packages/ui5-app/webapp/controller/Main.controller.js
- packages/ui5-app/webapp/view/Main.view.xml
- packages/ui5-tooling-modules/lib/middleware.js
- packages/ui5-tooling-modules/lib/task.js
- packages/ui5-tooling-modules/lib/util.js
- packages/ui5-tooling-modules/package.json
- yarn.lock
Enhanced the transpiling script to also follow the dependencies
chain, e.g. if a module is resolve from another NPM package (not
via the UI5 tooling) then the dependencies of this UI5 module needs
to be also covered by the task. For the middleware the client will
follow the dependencies and request them from the server.
> feat(ui5-tooling-modules): ignore UI5 modules for transpiling

- packages/ui5-tooling-modules/lib/util.js
When using `nodePolyfills` before `nodeResolve` and `commonJS` it may happen that dependencies matching the name of built-in node modules are not going to be resolved and included anymore.
> fix(ui5-tooling-modules): add node polyfills later

- packages/ui5-middleware-cfdestination/package.json
- packages/ui5-middleware-iasync/package.json
- packages/ui5-middleware-index/package.json
- packages/ui5-middleware-livecompileless/package.json
- packages/ui5-middleware-livereload/package.json
- packages/ui5-middleware-livetranspile/package.json
- packages/ui5-middleware-onelogin/package.json
- packages/ui5-middleware-servestatic/package.json
- packages/ui5-middleware-simpleproxy/package.json
- packages/ui5-middleware-stringreplacer/package.json
- packages/ui5-middleware-webjars/package.json
- packages/ui5-task-compileless/package.json
- packages/ui5-task-flatten-library/package.json
- packages/ui5-task-i18ncheck/package.json
- packages/ui5-task-minify-xml/package.json
- packages/ui5-task-pwa-enabler/package.json
- packages/ui5-task-stringreplacer/package.json
- packages/ui5-task-transpile/package.json
- packages/ui5-task-zipper/package.json
- packages/ui5-tooling-modules/package.json
To get a comprehensive metadata database as well as to display data in the UI5 community website, metadata is necessary in the respective packages.
For this purpose, a subitem is created in `package.json` with the name `ui5-community` similar to the already existing item `ui5`.
In this subitem two arrays are added with the name `types` and `tags`.
In `types` the types will be contained, which can be multiple for each package. For example: "task" or "middleware".
In `tags` several free descriptive names of the package can be entered.
The explicit specification of these parameters makes the extraction much easier, instead of pulling them out of yaml or json files.
> chore: add metadata to `package.json` for all packages for ui5-community website

- packages/ui5-middleware-stringreplacer/lib/stringreplacer.js
- packages/ui5-task-stringreplacer/lib/stringreplacer.js
If there were no strings provided, the build would fail after a while and the middelware would get in an endless loop and you'd have to kill the node ùi5 serve` process (and the live reload would keep running). 
With this PR a check is done and the user is warned in case of the middleware and there is no attempt to replace any strings. In the case of the build taks we raise an error and stop the build to avoid that builds are completed while missing strings intended for production.
> fix(ui5-middleware/task-stringreplacer): handle missing strings

- packages/ui5-app/package.json
- packages/ui5-app/webapp/controller/Thirdparty.controller.js
- packages/ui5-tooling-modules/lib/util.js
- pnpm-lock.yaml
Reordered the rollup plugins to properly ensure that the entries `browser`, `module` and `main` in the `package.json` are considered properly while bundling. Moving the `pnpm-resolve` at the end as fallback if the module id can't be resolve via any other plugin. Now the bundling works properly for all use-cases: `chart.js`, `tui-image-editor`, `supabase`, `xslx`, `firebase`...
> fix(ui5-tooling-modules): bundling to consider browser, module, main

- .eslintignore
- packages/ui5-app/lib/firebase.js
- packages/ui5-app/webapp/controller/Thirdparty.controller.js
- packages/ui5-tooling-modules/lib/util.js
- pnpm-lock.yaml
To support special scenarios like `firebase` we need to create local bundle definitions to package all individual modules into a single bundle, otherwise this leads to problems that different modules aren't aware of each other. 
Now the ui5-tooling-modules can read project local bundle definitions via the app name + the path in the app folder, e.g. `ui5-app/lib/firebase`. With this module name the UI5 can also load the bundle via the `ui5-tooling-modules` extension.
> feat(ui5-tooling-modules): support app-local bundle defs

- packages/ui5-app/ui5.yaml
- packages/ui5-tooling-modules/lib/task.js
- packages/ui5-tooling-modules/package.json
- pnpm-lock.yaml
When using the configuration option addToNamespace 3rd party modules
will now be moved into the project namespace in the thirdparty folders
and the used module names in JS and XML files will be prefixed with
the projectNamespace+thirdparty. This ensures that 3rd party modules
are packaged locally within the application and do not conflict globally
with other modules.
> feat(ui5-tooling-modules): support name-spacing of modules

- packages/ui5-task-zipper/README.md
There was a copy/past error in the readme sample
> fix: ui5 task zipper readme

- packages/ui5-middleware-livereload/README.md
- packages/ui5-middleware-livereload/lib/livereload.js
Currently, using the livereload-middleware does not support running in virtualized filesystems, such as WSL 2.0
Adding configuration to enable/disable Chokidar Legacy polling allows a user to overcome this issue
> Add support for use of chokidar legacy polling

- packages/ui5-middleware-cfdestination/lib/cfdestination.js
> fix(ui5-middleware-cfdestination): use correct xsappPath when using custom xsappJson filename

- packages/ui5-app-ts/ui5.yaml
Noticed in #665 livereload is not working in this example -> added `ts` files to the watcher.
> chore(ts-app): enable live reload for ts sources

- packages/ui5-tooling-transpile/lib/middleware.js
I had trouble when filetypes like images are handled by the transpile middleware. 
So I figured it helps to always exclude them, since there shouldn't be any purpose to transpile images.
> default exclude images in [ui5-transpile-middleware]

- packages/ui5-tooling-modules/lib/util.js
- packages/ui5-tooling-modules/package.json
- pnpm-lock.yaml
With `@rollup/plugin-node-resolve` version >13 the tooling extension ui5-tooling-modules is producing issues in external projects, the reasoning isn't clear yet and still needs to be verified. 
Between @rollup/plugin-node-resolve 13.3.0 and 14.0.0 something changed which leads to corrupt bundles for other projects - locally in the ecosystem it seems to work. The following change adopted the module resolution:
https://github.com/rollup/plugins/commit/886debae6b1d9f00c897c866a4c4c6975a5d47db
Fixes #673
> fix(ui5-tooling-modules): revert to node-resolve v13 due to bundling issues

- packages/ui5-app-module/Chart.js
- packages/ui5-app-ts/package.json
- packages/ui5-app/package.json
- packages/ui5-app/webapp/controller/Thirdparty.controller.js
- packages/ui5-middleware-cfdestination/package.json
- packages/ui5-middleware-onelogin/package.json
- packages/ui5-task-cachebuster/package.json
- packages/ui5-tooling-modules/lib/rollup-plugin-amd-custom.js
- packages/ui5-tooling-modules/package.json
- pnpm-lock.yaml
In special cases the custom AMD plugin for rollup detects an ES module as AMD module and fails while parsing it. To avoid those issues, the parsing is try/catched so that in case of parsing issues, the custom AMD plugin will ignore the module.
Fixes https://github.com/SAP-samples/ui5-typescript-tutorial/issues/9
> fix(ui5-tooling-modules): make amd bundling more robust for side effects

- packages/ui5-task-cachebuster/lib/cachebuster.js
- packages/ui5-task-compileless/lib/compileLess.js
- packages/ui5-task-flatten-library/lib/flatten-library.js
- packages/ui5-task-i18ncheck/lib/i18ncheck.js
- packages/ui5-task-pwa-enabler/lib/pwaEnabler.js
- packages/ui5-task-zipper/lib/zipper.js
- packages/ui5-tooling-modules/lib/task.js
- packages/ui5-tooling-stringreplace/lib/task.js
- packages/ui5-tooling-transpile/lib/task.js
This PR implements the `determineRequiredDependencies` hook for all tasks. With that consumers of these tasks experience better performance when using UI5 Tooling V3.
For further info see https://sap.github.io/ui5-tooling/stable/pages/extensibility/CustomTasks/#required-dependencies
> fix: implement determineRequiredDependencies

- packages/ui5-app-simple/ui5.yaml
- packages/ui5-app-ts/.babelrc
- packages/ui5-app-ts/.babelrc.json
- packages/ui5-app-ts/.browserslistrc
- packages/ui5-app-ts/ui5.yaml
- packages/ui5-app-ts/webapp/controller/Main.controller.ts
- packages/ui5-app/ui5.yaml
- packages/ui5-app/webapp/test/e2e/interaction.test.js
- packages/ui5-lib-ts/ui5.yaml
- packages/ui5-tooling-transpile/README.md
- packages/ui5-tooling-transpile/lib/middleware.js
- packages/ui5-tooling-transpile/lib/task.js
- packages/ui5-tooling-transpile/lib/util.js
- packages/ui5-tooling-transpile/package.json
- packages/ui5-tooling-transpile/test/__assets__/external/.babelrc
- packages/ui5-tooling-transpile/test/__assets__/external/.browserslistrc
- packages/ui5-tooling-transpile/test/util.test.js
- pnpm-lock.yaml
Cleanup of configuration options and properly describe their meaning and their usage. Explain the usage of external configuration for Babel and the browserslist.
Defaults the `@babel/preset-env` to use the `defaults` setting from browserslist which equals `>0.5%, last 2 versions, Firefox ESR, not dead` as the target to transpile the classes to.
Renamed the `transpileAsync` to `transformAsyncToPromises` to clarify that this transpiles `async/await` to `Promises` instead of using the regenerator runtime which is the default of Babel. In case of transpiling `async/await` with an older browserslist configuration this option is recommended to be enabled to avoid CSP compliance issues with the regenerator runtime.
> feat(ui5-tooling-transpile): align and clean-up configuration options

- packages/ui5-tooling-transpile/lib/util.js
- showcases/ui5-tsapp/.babelrc
- showcases/ui5-tsapp/.browserslistrc
order of the presets is important: last preset is applied first which means the .babelrc config should look like that:
```
"presets": [
"@babel/preset-env",        // applied 3rd
"transform-ui5",            // applied 2nd
"@babel/preset-typescript"  // applied 1st
],
```
so, first transpile typescript, then ES modules/classes to UI5 and finally transpile the rest to the target browser env.
> fix(ui5-tooling-transpile): correct order of presets

- packages/ui5-tooling-transpile/lib/middleware.js
- packages/ui5-tooling-transpile/lib/task.js
- packages/ui5-tooling-transpile/lib/util.js
- pnpm-lock.yaml
To benefit from out of the box support of other Babel plugins the `filename` needs to point to the proper `fsPath` of the resource. In Tooling 3.0 this works out-of-the-box and for 2.0 we are using a workaround (which will be removed with the full upgrade to UI5 Tooling 3.0).
> fix(ui5-tooling-transpile): use proper fs path for resource tranform

- packages/karma-ui5-transpile/README.md
- packages/karma-ui5-transpile/lib/index.js
- packages/karma-ui5-transpile/package.json
- packages/ui5-tooling-transpile/README.md
- packages/ui5-tooling-transpile/lib/middleware.js
- packages/ui5-tooling-transpile/lib/task.js
- packages/ui5-tooling-transpile/lib/util.js
- showcases/ui5-app-simple/ui5.yaml
- showcases/ui5-app-simple/webapp/controller/App.controller.js
- showcases/ui5-app-simple/webapp/controller/Main.controller.js
- showcases/ui5-app/ui5.yaml
- showcases/ui5-tsapp-simple/ui5.yaml
- showcases/ui5-tsapp/.eslintrc.js
- showcases/ui5-tsapp/ui5.yaml
- showcases/ui5-tslib/ui5.yaml
The programming language is now derived by the existence of the tsconfig.json which means the project is a TypeScript project and if no tsconfig.json is present the tooling extension assumes the project to be of type JavaScript.
The decision of the tooling extension can be overruled by providing config options in the ui5.yaml. E.g. the TypeScript transpiling can be enabled by setting the transformTypeScript option to true. Setting it to false will overrule the existence of tsconfig.json and just transpile JavaScript.
The config option transpileTypeScript renamed to transformTypeScript.
Adopted the tooling extension task and middleware as well as the Karma preprocessor to use the getConfiguration function to normalize the configuration.
> feat(ui5-tooling-transpile): rework to avoid configurations for default usage

- packages/ui5-task-zipper/README.md
- packages/ui5-task-zipper/lib/zipper.js
- packages/ui5-task-zipper/test/__assets__/ui5-app-simple/ui5.includeSomeDeps.yaml
- packages/ui5-task-zipper/test/__assets__/ui5-app/ui5.includeSomeDeps.yaml
- packages/ui5-task-zipper/test/zipper.test.js
The task has been extended to allow to specify the list of UI5 dependencies to be included in the final zip analog to the builder settings includeDependency. The configuration option includeDependencies now also accepts an array of strings providing the UI5 dependency name which is the name specifed in the ui5.yaml > metadata > name property.
```yaml
builder:
customTasks:
- name: ui5-task-zipper
afterTask: generateVersionInfo
configuration:
archiveName: simpleapp
includeDependencies:
- sap.ui.layout
```
Fixes #550
> feat(ui5-task-zipper): allow to specify the deps to include

- packages/ui5-tooling-modules/README.md
- packages/ui5-tooling-modules/lib/task.js
- packages/ui5-tooling-modules/lib/util.js
- packages/ui5-tooling-modules/package.json
- pnpm-lock.yaml
- showcases/ui5-app/package.json
- showcases/ui5-app/ui5.yaml
This feature enables the ui5-tooling-modules tooling extension to include assets from npm packages. The assets to be included can be either just the npm package name including all assets or a list of glob patterns to select the assets to be included. The assets will be put into the proper folder like the required dependencies. In case of including JS files, those files will not be processed by the ui5-tooling-modules just copied.
```yaml
builder:
customTasks:
- name: ui5-tooling-modules-task
afterTask: ui5-tooling-transpile-task
configuration:
includeAssets:
"@octokit/core":
- "dist-web/*.map"
"tui-image-editor":
- "dist/**/*.css"
- "dist/**/*.svg"
```
Fixes #590
> feat(ui5-tooling-modules): include assets of npm packages

- packages/ui5-tooling-modules/package.json
- pnpm-lock.yaml
- showcases/ui5-app/package.json
- showcases/ui5-app/ui5.yaml
- showcases/ui5-app/webapp/controller/Thirdparty.controller.js
- showcases/ui5-tsapp/package.json
- showcases/ui5-tsapp/ui5.yaml
- showcases/ui5-tsapp/webapp/controller/Main.controller.ts
The dependency `ignore-walk` has been added by accident to the showcase instead of the tooling extensions. Will be fixed with this change - plus some more 3rd party libs included for testing.
Fixes #713
> fix(ui5-tooling-modules): include ignore-walk as dependency

- packages/karma-ui5-transpile/README.md
- packages/karma-ui5-transpile/lib/index.js
- packages/karma-ui5-transpile/package.json
- pnpm-lock.yaml
- showcases/ui5-tsapp/karma-ci-cov.conf.js
- showcases/ui5-tslib/karma-ci-cov.conf.js
The karma-coverage preprocessor instruments the final content of the Babel transformation done by the karma-ui5-transpile preprocessor. This leads to wrong code coverage results since the UI5 AMD-like module is instrumented rather than the JS code without TypeScript. Therefore the karma-ui5-transpile preprocessor injects the istanbul plugin into the Babel transformation that it instruments at the right point in time.
With this change the "coverage" preprocessor must not be used in combination with the "ui5-transpile". Only the "coverage" reporter can be used to create the reports finally.
> fix(karma-ui5-transpile): also instrument in Babel transformation

- packages/ui5-tooling-transpile/lib/task.js
- showcases/ui5-tsapp/package.json
- showcases/ui5-tsapp/tsconfig.json
- showcases/ui5-tslib/package.json
Adding `d.ts.map` support to allow to "Go to Sources Definition" in VSCode. We need to post-process the `d.ts.map` to correct the source mapping to the sources of the project. Due to the virtual paths, this doesn't work automatically.
With this fix, we are in general switching back to using `types` in the `tsconfig.json`. The `typeRoots` seem to work semi-optimal in case of using dependencies as the `typeRoots` are scanning the given folder and its subfolders for `index.d.ts` files. Using `types` the NPM package needs to provide the `types` mapping to the `index.d.ts` file in the `package.json` but in general we do not run into the [`TS2688` issue](https://github.com/microsoft/TypeScript/issues/27956) when running type checking. With the solution using `types` all scenarios are working …
> fix(ui5-tooling-transpile): add support for d.ts source maps

- .github/workflows/release-auto.yml
- .github/workflows/release-manual.yml
- .github/workflows/tests-e2e.yml
- .github/workflows/tests.yml
- CONTRIBUTING.md
- package.json
- packages/ui5-tooling-transpile/lib/util.js
- pnpm-lock.yaml
The target browsers configuration for Babel can be passed via the env var "ui5_tooling_transpile__targetBrowsers" when no .babelrc or .browserslistrc is present and the configuration from the ui5.yaml is used. Dots and dashes are not allowed for environment variables and therefore we use underscores as alternative characters.
> fix(ui5-tooling-transpile): allow to inject targetBrowsers via env var

- packages/ui5-tooling-stringreplace/README.md
- packages/ui5-tooling-stringreplace/lib/middleware.js
- packages/ui5-tooling-stringreplace/lib/task.js
- packages/ui5-tooling-stringreplace/lib/util.js
add option to specify location of `.env` file.
required e.g. in monorepositories to share environment across packages.
> feat(stringreplace): add path to .env option

- packages/ui5-middleware-cfdestination/README.md
- packages/ui5-middleware-cfdestination/lib/cfdestination.js
- packages/ui5-middleware-cfdestination/package.json
- packages/ui5-middleware-cfdestination/test/dest-in-env.test.js
- packages/ui5-middleware-cfdestination/test/dest-in-env/ui5.yaml
- packages/ui5-middleware-cfdestination/test/dest-in-env/xs-app.json
- pnpm-lock.yaml
Provides the option to store destinations as JSON string inside in `.env` file variable. 
Extract from `ui5.yaml` that is using the new option:
```yaml
- name: ui5-middleware-cfdestination
afterMiddleware: compression
configuration:
authenticationMethod: "route"
allowServices: true
debug: true
xsappJson: "local-xs-app.json"
destinations: "$env:xsapp_dest"
```
P.S.
As I am new to `ava` which is used for testing I only wrote a positive test. I didn't manage it to also implement a negative test 😊.
Best regards,
Ludwig
> feat(ui5-middleware-cfdestination): allow dest. to be maintained in .env

- packages/karma-ui5-transpile/package.json
- packages/ui5-middleware-cap/package.json
- packages/ui5-middleware-cfdestination/package.json
- packages/ui5-middleware-iasync/package.json
- packages/ui5-middleware-index/package.json
- packages/ui5-middleware-livecompileless/package.json
- packages/ui5-middleware-livereload/package.json
- packages/ui5-middleware-servestatic/package.json
- packages/ui5-middleware-simpleproxy/package.json
- packages/ui5-middleware-webjars/package.json
- packages/ui5-task-cachebuster/package.json
- packages/ui5-task-compileless/package.json
- packages/ui5-task-flatten-library/package.json
- packages/ui5-task-i18ncheck/package.json
- packages/ui5-task-minify-xml/package.json
- packages/ui5-task-pwa-enabler/package.json
- packages/ui5-task-zipper/package.json
- packages/ui5-tooling-modules/package.json
- packages/ui5-tooling-stringreplace/package.json
- packages/ui5-tooling-transpile/package.json
Adopted the package.json versions and making a breaking change to finally trigger a major version change with Lerna.
BREAKING CHANGE: The support for UI5 Tooling V2 has been removed
Fixes: #770
Closes: #648
> feat: prepare versions for release for UI5 Tooling V3

- packages/karma-ui5-transpile/lib/index.js
- packages/ui5-tooling-transpile/lib/util.js
- packages/ui5-tooling-transpile/test/__assets__/external/.babelrc
- packages/ui5-tooling-transpile/test/util.test.js
- showcases/ui5-tsapp/.babelrc
- showcases/ui5-tslib/.babelrc.json
TypeScript-based projects don't instrument test resources because
of the defaults used from nyc-config. Therefore, the istanbul
configuration must include the opts for the instrumentation defining
the include and exclude options.
> fix(karma-ui5-transpile): ensure to instrument test files 

- packages/ui5-tooling-modules/README.md
- packages/ui5-tooling-modules/lib/middleware.js
- packages/ui5-tooling-modules/lib/rollup-plugin-dynamic-imports.js
- packages/ui5-tooling-modules/lib/rollup-plugin-inject-esmodule.js
- packages/ui5-tooling-modules/lib/rollup-plugin-logger.js
- packages/ui5-tooling-modules/lib/rollup-plugin-pnpm-resolve.js
- packages/ui5-tooling-modules/lib/rollup-plugin-skip-assets.js
- packages/ui5-tooling-modules/lib/task.js
- packages/ui5-tooling-modules/lib/util.js
- packages/ui5-tooling-modules/test/__snap__/@luigi-project/container.js
- packages/ui5-tooling-modules/test/util.test.js
- pnpm-lock.yaml
- showcases/ui5-tsapp/package.json
- showcases/ui5-tsapp/ui5.yaml
If a project needs to consume an NPM package which makes use of dynamic imports to load arbitrary scripts, one can decide to keep the `import(...)` call and omit the transpiling into AMDs' `require(...)` call.
This is e.g. necessary for `@luigi-project/container` to support loading custom elements as ES modules from another location. To do so, you need to do the following:
* Add a dependency to `@luigi-project/container`
* Extend the `ui5-tooling-modules` configuration to tell it to keep dynamic imports for this module
* Example to define reuse configuration centrally in `ui5.yaml`: https://github.com/ui5-community/ui5-ecosystem-showcase/blob/3675ed95b8f6408fd9fe9e36a4fc5aba9ec10518/showcases/ui5-tsapp/ui5.yaml#L10-L13 and reuse it in the task and middleware)
* Reuse in task: …
> fix(ui5-tooling-modules): allow to skip convert of dynamic imports

- packages/ui5-tooling-transpile/README.md
- packages/ui5-tooling-transpile/lib/util.js
- packages/ui5-tooling-transpile/test/util.test.js
In case of using the UI5 Tooling binary in e.g. the `ui5-tsapp-simple`, Babel fails to resolve the presets and plugins. This is most likely related to the monorepos setup using npm and using a globally installed binary is lacking the information where to resolve the presets and plugins from. Now, the `ui5-tooling-transpile` resolves the presets and plugins on its own.
> fix(ui5-tooling-transpile): support preset/plugin resolution with UI5 tooling binary

- packages/ui5-tooling-transpile/lib/task.js
- packages/ui5-tooling-transpile/lib/util.js
- packages/ui5-tooling-transpile/package.json
- packages/ui5-tooling-transpile/test/__assets__/external/.babelrc
- packages/ui5-tooling-transpile/test/__assets__/typescript/tsconfig.json
- pnpm-lock.yaml
Use `comment-json` to parse the tsconfig.json and the babel config in
order to allow comments in those files. This is also allowed inside
VSCode when editing these files.
Fixes https://github.com/ui5-community/ui5-ecosystem-showcase/issues/803
> fix(ui5-tooling-transpile): support comments in ts config and babel config

- packages/karma-ui5-transpile/lib/index.js
- packages/karma-ui5-transpile/package.json
- packages/ui5-tooling-transpile/lib/util.js
- packages/ui5-tooling-transpile/test/util.test.js
- showcases/ui5-tsapp/karma-ci-cov.conf.js
Ensure to resolve all presets and plugins in the babel configuration options before running the transform functions - which is necessary for pnpm monorepo scenarios or when running a build or serve with the globally installed UI5 tooling.
fix(karma-ui5-transpile): use new preprocess step for babel config
To check the existence of the istanbul plugin in the babel configuration the plugin hooks into the new pre-process phase of the createBabelConfig function from ui5-tooling-transpile and now is able to handle the babel plugin config entries which can be string, an array or a config item.
Fixes #810
> feat(ui5-tooling-transpile): resolve presets/plugins for babel config options

- packages/ui5-middleware-cfdestination/lib/cfdestination.js
The mime info is derived from the `content-type` header. The regex to identify this header wasn't specific enough. Now the header is identified correctly and side-effect with headlers like: `X-Content-Type-Options` are prevented.
Fixes: #797
> fix(ui5-middleware-cfdestination): fixed mime info detection

- packages/ui5-middleware-cfdestination/README.md
- packages/ui5-middleware-cfdestination/lib/cfdestination.js
- packages/ui5-middleware-index/README.md
- packages/ui5-middleware-index/lib/index.js
To enable support for the UAA flow, the option `xfwd` of the
`http-proxy-middleware` is necessary to forward the redirect
host information for the SAML auth flow.
In the `xs-security.json` you need to configure the UI5 server
URL:
```json
{
"xsappname": "sample-ui5-uaa-uaa",
[...],
"oauth2-configuration": {
"redirect-uris": [
"http://localhost:8080/login/callback",
"http://localhost:5000/login/callback"
]
}
}
```
next to the approuter server URL, so that it gets accepted
by the SAML auth flow as a callback.
The change also makes the disabling of the welcome file
configurable to allow the usage of the redirect handling
of the approuter.
The `ui5-middleware-index` has been extended to play properly
together with the `ui5-middleware-cfdestination` so that the
handling of the welcomeFile …
> fix(ui5-middleware-cfdestination): support UAA flow

- packages/ui5-middleware-simpleproxy/README.md
- packages/ui5-middleware-simpleproxy/lib/proxy.js
- showcases/ui5-app/ui5.yaml
- showcases/ui5-app/webapp/controller/Main.controller.js
- showcases/ui5-app/webapp/controller/ODataV4.controller.js
- showcases/ui5-app/webapp/i18n/i18n.properties
- showcases/ui5-app/webapp/i18n/i18n_en.properties
- showcases/ui5-app/webapp/manifest.json
- showcases/ui5-app/webapp/view/Main.view.xml
- showcases/ui5-app/webapp/view/ODataV4.view.xml
This change ensures the compatibility with express/connect servers by using the middlware util from the ui5 tooling to determine the request path.
Support opening of URLs in the browser causing ERR_CONTENT_DECODING_FAILED by using the response-interceptor of the http-proxy-middleware to decode the response. The issue didn't appear for XMLHttpRequests.
Enhanced the demo application to proxy the Tripin service via the ui5-middleware-simpleproxy.
> fix(ui5-middleware-simpleproxy): support for express/connect servers

- packages/ui5-tooling-transpile/lib/util.js
As soon as a pattern is used in the Babel config, a dummy filename needs to be provided!
> fix(ui5-tooling-transpile): ensure loadPartialConfigAsync works with include/excludes/ignore patterns

- packages/cds-plugin-ui5/cds-plugin.js
- packages/cds-plugin-ui5/lib/createPatchedRouter.js
- packages/ui5-middleware-cfdestination/lib/cfdestination.js
- packages/ui5-middleware-index/lib/index.js
- packages/ui5-middleware-livecompileless/lib/index.js
- packages/ui5-middleware-simpleproxy/lib/proxy.js
- packages/ui5-middleware-webjars/lib/index.js
- packages/ui5-tooling-modules/lib/middleware.js
- packages/ui5-tooling-stringreplace/lib/middleware.js
- packages/ui5-tooling-transpile/lib/middleware.js
- packages/ui5-tooling-transpile/package.json
- pnpm-lock.yaml
- showcases/ui5-app/webapp/controller/ODataV2.controller.js
This fix aligns the request path handling of all middlewares which
rely on the request url to retrieve the proper resource. In case of
loading resources via express.Router the `req.url`, `req.baseUrl`,
and `req.originalUrl` contains all relevant information to know the
context path and the local path. The `baseUrl` and the `originalUrl`
must not be overwritten by middlewares to be able to identify the
source context path of the request.
This cleanup is a precondition to ge the nested routing for the
combination of `cds-plugin-ui5`, `ui5-middleware-cfdestination`,
`approuter` and an underlying UAA.
Related to discussion of https://github.com/ui5-community/ui5-ecosystem-showcase/issues/817
> fix: consistent request path handling of all middlewares

- README.md
- packages/ui5-middleware-cfdestination/lib/cfdestination.js
- packages/ui5-middleware-cfdestination/package.json
- packages/ui5-middleware-cfdestination/test/websocket.test.js
- packages/ui5-middleware-cfdestination/test/websocket/xs-app.json
- packages/ui5-middleware-simpleproxy/README.md
- packages/ui5-middleware-simpleproxy/lib/proxy.js
- packages/ui5-middleware-simpleproxy/package.json
- packages/ui5-middleware-simpleproxy/test/index.html
- packages/ui5-middleware-simpleproxy/test/proxy.test.js
- packages/ui5-middleware-websocket/README.md
- packages/ui5-middleware-websocket/lib/echo.js
- packages/ui5-middleware-websocket/lib/expressws.js
- packages/ui5-middleware-websocket/lib/hook.js
- packages/ui5-middleware-websocket/lib/websocket.js
- packages/ui5-middleware-websocket/package.json
- packages/ui5-middleware-websocket/ui5.yaml
- pnpm-lock.yaml
- showcases/ui5-app/package.json
- showcases/ui5-app/ui5-dist.yaml
- showcases/ui5-app/ui5-min.yaml
- showcases/ui5-app/ui5.yaml
- showcases/ui5-app/webapp/controller/Main.controller.js
- showcases/ui5-app/webapp/manifest.json
- showcases/ui5-app/webapp/test/unit/controller/Main.controller.js
- showcases/ui5-app/webapp/view/Main.view.xml
- showcases/ui5-app/xs-app.json
This commit introduces a new middleware package `ui5-middleware-websocket`
which provides helper functions to create WebSocket middlewares inside the
UI5 server:
```js
const websocket = require("ui5-middleware-websocket/lib/websocket");
/**
* WebSocket middleware to act as an echo service.
*
* @param {object} parameters Parameters
* @param {@ui5/logger/Logger} parameters.log Logger instance
* @returns {Function} Middleware function to use
*/
module.exports = ({ log }) => {
return websocket(function echo(ws, req /*, next */) {
ws.on("message", function (message) {
log.info(`message: ${message}`);
ws.send(`echo ${message}`);
});
log.info(`Connection established with ${req.url}`);
});
};
```
The function `websocket` provided by the module:
`const websocket = …
> feat(ui5-middleware-websocket): enable websocket support for UI5 server

- packages/cds-plugin-ui5/README.md
- packages/cds-plugin-ui5/cds-plugin.js
- packages/cds-plugin-ui5/lib/applyUI5Middleware.js
- packages/cds-plugin-ui5/lib/createPatchedRouter.js
- packages/cds-plugin-ui5/lib/findUI5Modules.js
- pnpm-lock.yaml
- showcases/cds-bookshop/app/ui5-bookshop/package.json
- showcases/cds-bookshop/app/ui5-bookshop/ui5-workspace-test.yaml
- showcases/cds-bookshop/app/ui5-bookshop/ui5.yaml
- showcases/cds-bookshop/package.json
The plugin can be configured using the `cds-plugin-ui5` section in the `package.json`. To define a custom configFile for any module you can add a configuration object for each module in the `modules` section:
```json
{
"name": "cds-bookshop",
[...]
"cds": {
[...]
"cds-plugin-ui5": {
"modules": {
"ui5-bookshop": {
"configFile": "ui5.yaml",
"workspaceConfigFile": "ui5-workspace.yaml",
"workspaceName": "default",
"versionOverride": "1.117.0"
}
}
}
}
}
```
The key is the `moduleId` which is either the directory name for local apps in the `app` directory of the CAP server or for dependencies the `name` from the `package.json`. As value you can specify an alternative `configFile`, `workspaceConfigFile`, `workspaceName`, and/or `versionOverride`. The location of the config files are relative to …
> feat(cds-plugin-ui5): support for configuration options

- packages/cds-plugin-ui5/README.md
- packages/cds-plugin-ui5/lib/findUI5Modules.js
- showcases/cds-bookshop-ui5-viewer/ui5.yaml
by default the mount path is derived from the "metadata/name" and can be overridden by "customConfiguration/mountPath" or by "customConfiguration/cds-plugin-ui5/mountPath" or by the following configuration entry in the package.json of CAP server: "cds/cds-plugin-ui5/modules/%moduleId%/mountPath"
> fix(cds-plugin-ui5): flexible mount path configuration

- packages/ui5-task-cachebuster/README.md
The `uglify` task has been removed with the UI5 Tooling v3 and mentions thereof lead to a build error.
> fix(ui5-task-cachebuster): update docu for afterTask configuration

- packages/ui5-tooling-transpile/lib/util.js
> fix(ui5-tooling-transpile): re-enable inline config in ui5.yaml

- packages/ui5-tooling-stringreplace/lib/middleware.js
- packages/ui5-tooling-stringreplace/package.json
- packages/ui5-utils-express/lib/intercept.js
- pnpm-lock.yaml
- showcases/ui5-app/ui5.yaml
- showcases/ui5-app/webapp/includes/iWillBeTranspiled.js
The stringreplace middleware must not be the last middleware in the chain and therefore should only intercept the response rather than sending the response. This allows other middlewares such as the transpiling to run afterwards.
The middleware must be executed before any other middleware which finally sends the response (like the transpile or modules middleware). When called, it hooks into the functions of the server response and collects the content to finally rewrite it. The final send will be left to the UI5 tooling development server or other middlewares.
Fixes #665
> feat(ui5-tooling-stringreplace): allow combination with other middlewares

- packages/ui5-middleware-ui5/lib/findUI5Modules.js
It doesn't work in case no config is provided because of an error it goes into the catch. This fix will make sure it takes the default value in case no config is provided
> fix: make it work without config

- packages/ui5-tooling-less/lib/task.js
- showcases/ui5-app/ui5.yaml
- showcases/ui5-app/webapp/css/sap_horizon/style.less
- showcases/ui5-app/webapp/css/sap_horizon_dark/style.less
To ensure that resources can be found with the specified globs in the lessToInclude configuration parameter, they have to be resolved relative to the app namespace.
Fixes #896
> fix(ui5-tooling-less): resolve globs relative to app namespace

- packages/cds-plugin-ui5/cds-plugin.js
Instead of supporting both variants, activate hook in object vs. Promise, the activate hook has been completely removed to avoid a switch statement based on version. This ensures simplicity of code and it wasn't needed at all...
Fixes #899
> fix(cds-plugin-ui5): remove activation hook since it's not needed

- packages/ui5-tooling-modules/lib/task.js
- packages/ui5-tooling-modules/lib/util.js
Images can't be read as UTF-8 and stored again like this as they are a binary file format and therefore must be read as stream and stored via stream.
Fixes: #902
> fix(ui5-tooling-modules): copy resources as stream to not kill encoding

- packages/cds-plugin-ui5/README.md
- packages/cds-plugin-ui5/cds-plugin.js
As dynamic imports are only supported in JEST with Node.js 21 and the experimental flag: NODE_OPTIONS=--experimental-vm-modules we by default disable the cds-plugin-ui5 to avoid issues. It can be forcefully activated by CDS_PLUGIN_UI5_ACTIVE=true when testing in the environment as described above.
Fixes #901
> fix(cds-plugin-ui5): disable plugin for JEST test execution

- packages/ui5-tooling-modules/lib/middleware.js
> fix(ui5-tooling-modules): keep non-text content alive using middleware

- packages/cds-plugin-ui5/lib/log.js
`cds-ui5-plugin` was logged into the console when using the package instead of `cds-plugin-ui5`.
> fix(cds-plugin-ui5): package name in logs

- packages/karma-ui5-transpile/lib/index.js
- packages/ui5-tooling-transpile/lib/middleware.js
- packages/ui5-tooling-transpile/lib/task.js
- packages/ui5-tooling-transpile/lib/util.js
- packages/ui5-tooling-transpile/test/util.test.js
- showcases/ui5-tsapp/ui5.yaml
- showcases/ui5-tsapp/webapp/Component.ts
With this feature the task of `ui5-tooling-transpile` supports the generation of the control interfaces if the option `generateTsInterfaces` is set to `true`.
Fixes #919
> feat(ui5-tooling-transpile): support generation of interfaces in task

- packages/ui5-task-flatten-library/README.md
With versions 3.8.0 of the `ui5/cli` a new feature was introduced that completes and extends the `ui5-task-flatten-library`.
With this chenage, the README of the `ui5-task-flatten-library` is updated to reference that new feature of UI5 Tooling.
Details:
- [Blog Post](https://blogs.sap.com/?p=1898173?source=email-global-notification-bp-new-in-tag-followed)
- [Feature in CLI](https://github.com/SAP/ui5-cli/pull/665)
> fix(ui5-task-flatten-library): update readme with ui5 tooling cli information

- packages/cds-plugin-ui5/cds-plugin.js
fixes: #946
maybe there is a better option like ```cds.env._home```?
> fix: prefere cds.env._home over just current process.cwd

- packages/ui5-tooling-transpile/lib/util.js
- packages/ui5-tooling-transpile/test/__assets__/external-js/.babelrc
- packages/ui5-tooling-transpile/test/__assets__/external-js/.browserslistrc
- packages/ui5-tooling-transpile/test/__assets__/external-js/babel.config.js
- packages/ui5-tooling-transpile/test/util.test.js
> fix(ui5-tooling-transpile): support JS-based babel config files

- packages/ui5-tooling-stringreplace/lib/util.js
I adjusted fetching the MimeInfo fetching as currently the type for all .ts files will result in "video/mp2t" and therefore will be ignored by the stringreplace-task. 
With this change the stringreplace-task can also detect and replace strings in any TypeScript files.
Please also refer to this issue: https://github.com/ui5-community/ui5-ecosystem-showcase/issues/979
> Adjusted ui5-tooling-stringreplace to work with .ts files

- packages/ui5-middleware-serveframework/README.md
- packages/ui5-middleware-serveframework/lib/index.js
- packages/ui5-middleware-serveframework/package.json
- pnpm-lock.yaml
Allow to override ui5 version coming from `$yourapp/ui5.yaml` file with environment variable. This allows to store ui5 version used by multiple projects in a single place.
> feat(ui5-middleware-serveframework): provide custom ui5 version from env variable

- packages/ui5-tooling-modules/lib/middleware.js
- packages/ui5-tooling-modules/lib/task.js
- packages/ui5-tooling-modules/lib/util.js
When modules have dependencies to unknown or native modules (e.g. "fs") then the tooling extension tries to include them but cannot find and open them during the build process which leads to an empty bundle.
In addition, added a proper error logging in case of bundling errors to see the stack trace for the build and the middleware. The build will stop but the middleware just prints the issue without stopping the server.
Fixes #977
> fix(ui5-tooling-modules): ignore unkown modules for bundling

- packages/ui5-tooling-transpile/lib/task.js
This uses https://nodejs.org/api/url.html#urlpathtofileurlpath-options to make the path an absolute `file://` path that should be suitable for using with `import` on all platforms.
`require.resolve()` alone results in an absolute path on Windows which cannot be used.
> fix(ui5-tooling-transpile): create absolute path for the replaceVersion import

- packages/ui5-tooling-modules/README.md
- packages/ui5-tooling-modules/lib/util.js
Starting with `ui5-tooling-modules` version `3.7.0` every entry point must be resolved from a `dependency`. Entry points used from `devDependencies` or other dependencies are not included anymore for the generation of the modules bundles. 
This ensures that the used entry points are properly declared and scan tools can identify the NPM packages for the used thirdparty modules. It also ensures that if a dependency is used the proper thirdparty modules are also available as transitive dependencies.
> feat(ui5-tooling-modules): entry point modules must be project dependencies

- packages/ui5-tooling-less/lib/task.js
As of now the ui5-tooling-less-task is not working when the configuration parameter `lessToCompile` is provided as a single string value.
```yaml
customTasks:
- name: ui5-tooling-less-task
beforeTask: minify
configuration:
lessToCompile: 'theme/style.less'
```
A workaround is to use a list style. 
```yaml
customTasks:
- name: ui5-tooling-less-task
beforeTask: minify
configuration:
lessToCompile: 
- 'theme/style.less'
```
I stumbled across it when migrating an old project from a colleague to UI5 tooling v3. We used a custom less compile task supporting single values and the switch to the official UI5 tooling task made me struggling.
> fix: handle case when lessToCompile is provided as a string value

- packages/cds-plugin-ui5/README.md
- packages/ui5-middleware-cap/README.md
Add information about supported CAP runtime to readme of
- ui5-middleware-cap
- cds-plugin-ui5
> feat: Enhance readme

- packages/ui5-tooling-modules/lib/util.js
The regex to decide which file extensions are considered as entry points for the bundle was to vague and needs to be more precise to not match json file extensions with it as json files should be considered as resources.
> fix(ui5-tooling-modules): only consider js, cjs or mjs files as bundle entry points

- packages/ui5-task-zipper/README.md
Shouldn't this say `false`? If set to `true`, it will only generate the zip.
> docs(ui5-task-zipper): fix onlyZip option

- .gitignore
- packages/ui5-tooling-modules/README.md
- packages/ui5-tooling-modules/lib/middleware.js
- packages/ui5-tooling-modules/lib/util.js
* only scan the dependencies which are UI5 packages (either having a ui5.yaml or .ui5pkg marker file)
* avoid recursive scanning of packages
* add verbose logging information
* introduced persistent cache for middleware to store bundle info in `.ui5-tooling-modules` folder in the cwd with a hash to reduce the overhead of regenerating the bundle info without changes
Fixes #1052
> feat(ui5-tooling-modules): performance opt + persistent bundle info cache

- packages/ui5-tooling-transpile/lib/task.js
Fixes #1062 
and issues like the following:
```
> ui5 build --config=ui5.yaml --clean-dest --dest dist
info ProjectBuilder Preparing build for project zbasicrel
info ProjectBuilder   Target directory: dist
info ProjectBuilder Cleaning target directory...
info Project 1 of 1: ❯ Building application project zbasicrel...
info zbasicrel › Running task escapeNonAsciiCharacters...
info zbasicrel › Running task replaceCopyright...
info zbasicrel › Running task replaceVersion...
info zbasicrel › Running task ui5-tooling-transpile-task...
info builder:custom-task:ui5-tooling-transpile-task Create Babel configuration based on ui5.yaml configuration options...
info builder:custom-task:ui5-tooling-transpile-task Using browserslist configuration from ui5.yaml...
error …
```
> [ui5-tooling-transpile] fix for loading replaceVersion

- packages/ui5-tooling-modules/lib/middleware.js
- packages/ui5-tooling-modules/lib/rollup-plugin-webcomponents.js
- packages/ui5-tooling-modules/lib/util.js
> fix(ui5-tooling-modules): windows support and performance improvements

- packages/ui5-tooling-modules/lib/rollup-plugin-webcomponents.js
- packages/ui5-tooling-modules/lib/templates/WrapperControl.hbs
- packages/ui5-tooling-modules/lib/utils/WebComponentRegistry.js
- packages/ui5-tooling-modules/test/__snap__/4370bd2f/@ui5/webcomponents/dist/CheckBox.js
- packages/ui5-tooling-modules/test/__snap__/d726ec84/@ui5/webcomponents/dist/Panel.js
- showcases/ui5-tsapp-webc/webapp/controller/Main.controller.ts
- showcases/ui5-tsapp-webc/webapp/view/Main.view.xml
- showcases/ui5-tsapp-webc/webapp/view/form/FormPage.view.xml
* Test how custom data (or a variation) could be used to handle native properties (see below, _Open special properties/events_)
* Investigate how to implement `sap.ui.core.ISemanticFormContent` for the Multi Input?
* Is this even needed?
* What does the semantic form content do in UI5 anyway?
* ~~Should the `for` property of `@ui5/webcomponents/Label` be renamed to `labelFor` like in the original retrofits?~~
* **Answer**: No we will not align with the deprecated retrofit components. The custom elements metadata will be leading.
* ~~Is `InputElementsFormSupport` still needed for the latest WebC versions?~~
* ~~Seems to be replaced by an actual interface...~~
* **Answer**: No it is not needed anymore. The current web components implementation uses a newer internal interface approach, refer …
> feat(ui5-tooling-modules): support special UI5 settings for web components

- packages/ui5-tooling-modules/lib/rollup-plugin-webcomponents.js
- packages/ui5-tooling-modules/lib/templates/WrapperControl.hbs
- packages/ui5-tooling-modules/lib/utils/WebComponentRegistry.js
- packages/ui5-tooling-modules/test/__snap__/4370bd2f/@ui5/webcomponents/dist/CheckBox.js
- packages/ui5-tooling-modules/test/util.test.js
- showcases/ui5-tsapp-webc/webapp/controller/Main.controller.ts
- showcases/ui5-tsapp-webc/webapp/view/Main.view.xml
When the `enabled` (resp. `disabled`) property exists, we need to also apply the `sap/ui/core/EnabledPropagator` mixin to the control wrapper.
This way the `enabled` state is propagated along the control tree.
> fix(ui5-tooling-modules): apply sap/ui/core/EnabledPropagator mixin

- packages/ui5-middleware-serveframework/README.md
- packages/ui5-middleware-serveframework/lib/index.js
In some environments (e.g. Citrix 😖), the specified path is deleted daily and requires a new compilation every day.
To prevent this, new configuration options are added to store the libraries either in the project or in a separate custom path.
> feat(ui5-middleware-serverframework): custom path to save libs

- packages/ui5-tooling-modules/lib/middleware.js
- packages/ui5-tooling-modules/lib/rollup-plugin-webcomponents.js
- packages/ui5-tooling-modules/lib/templates/monkey_patches/MapValueState.hbs
- packages/ui5-tooling-modules/lib/templates/monkey_patches/RegisterAllEvents.hbs
- packages/ui5-tooling-modules/lib/templates/monkey_patches/RenderAttributeProperties.hbs
- packages/ui5-tooling-modules/lib/templates/monkey_patches/_Preamble.hbs
- packages/ui5-tooling-modules/test/__snap__/4370bd2f/@ui5/webcomponents-base.js
- packages/ui5-tooling-modules/test/__snap__/4370bd2f/@ui5/webcomponents.js
- packages/ui5-tooling-modules/test/__snap__/4370bd2f/@ui5/webcomponents/dist/CheckBox.js
- packages/ui5-tooling-modules/test/__snap__/d726ec84/@ui5/webcomponents.js
- packages/ui5-tooling-modules/test/__snap__/d726ec84/@ui5/webcomponents/dist/Panel.js
- packages/ui5-tooling-modules/test/__snap__/d726ec84/webcomponents-base.js
The `_mapValueState` function has been introduced with OpenUI5 `1.133.0-SNAPSHOT` and for older versions of UI5 we need to monkey patch it. This change introduces the monkey patch for the older versions. Otherwise this causes runtime issues when the value state is used for older versions.
> fix(ui5-tooling-modules): monkey patch mapValueState for older versions of UI5

- packages/dev-approuter/README.md
- packages/dev-approuter/lib/devApprouter.js
subject pretty much says it all: when the `dev-approuter` is used in hybrid scenarios (👋  CAP), 
then the `/my-jwt` route logs the current JWT/access token 
&rarr; helps in debugging auth(n,z) issues at dev time
docs are also in.
> feat: add custom /my-jwt route for debugging auth(n,z)

- packages/ui5-tooling-modules/lib/util.js
Adds one remaining place where package.json was not yet read from environment variable
> fix(ui5-tooling-modules): read location of package.json from environment variable everywhere

- packages/ui5-task-zipper/lib/zipper.js
With the help of @norbip, this PR fixes the `relativePath` option for cases that include escaped `\'` characters in the `manifest.json`. Also grabbing the stringified manifest from the `Component-preload.js` is a little more robust now.
> fix(ui5-task-zipper): escape stringified json

- packages/ui5-tooling-modules/lib/rollup-plugin-webcomponents.js
- packages/ui5-tooling-modules/lib/utils/WebComponentRegistry.js
The mechanism in the rollup plugin to generate the package wrappers relies on the lookup of the WebComponentsRegistry. When the packages and classes are known to the registry the packages will not be emitted anymore. In any case we nevertheless need to rebuild the web components metadata in case of changes to them. So the clear function now triggers a complete reload.
> fix(ui5-tooling-modules): ensure full rebuild after change of modules

- packages/ui5-tooling-modules/lib/templates/jsdoc/ClassHeader.hbs
- packages/ui5-tooling-modules/lib/utils/JSDocSerializer.js
- packages/ui5-tooling-modules/lib/utils/WebComponentRegistry.js
The @implements tag in the class header documentation for a wrapper class should list the JSDoc names of the implemented interfaces. In contrast, runtime metadata contains the runtime metadata names of the interfaces.
> fix(ui5-tooling-modules): add @implements tag to wrapper JSDoc

- .gitignore
- packages/ui5-middleware-serveframework/README.md
- packages/ui5-middleware-serveframework/lib/index.js
- showcases/ui5-app-simple/ui5.yaml
We would like to use serveframework also as part of our pull request voting. However, the installation takes quite some time if it installs all the libraries.
I understand that we cannot simply respect the ui5.yaml, as the data is stored for the user (in default behaviour), not for the project. 
However, when the project is used, it should consider the ui5.yaml.
~~This change introduces a new config setting that allows to specify the ui5.yaml that shall be used (defaults to ui5.yaml) in case a different one is used for testing for example.~~
UPDATE: Instead of making the config configurable I found a way to get the current config dependencies via the resources passed into the middleware function.
In case `saveLibsLocal` is set to true, it will filter the libraries to only match the ones …
> feat(ui5-middleware-serveframework): respect defined libraries in local config

- packages/cds-plugin-ui5/cds-plugin.js
Karma testing showed an "AggregateError" when the middlewares aren't fully applied to the router before the Karma test runs. Therefore, in non-lazy scenarios we need to wait until all middlewares have been properly applied.
Relates: https://github.com/ui5-community/ui5-ecosystem-showcase/pull/1224 (Solution proposal)
Relates: https://github.com/SAP-samples/cap-sflight/pull/1468 (Karma issue)
> fix(cds-plugin-ui5): wait for middlewares if not lazy

- packages/ui5-tooling-modules/README.md
- packages/ui5-tooling-modules/lib/postinstall.js
- packages/ui5-tooling-modules/package.json
- packages/ui5-tooling-transpile/README.md
- packages/ui5-tooling-transpile/lib/postinstall.js
- packages/ui5-tooling-transpile/package.json
- pnpm-lock.yaml
By using the command line argument `-rte` or `--register-tooling-extension`
the `ui5-tooling-transpile` and `ui5-tooling-modules` tooling extensions
add their configuration into the `ui5.yaml` of the project and in case
of the modules, it also modifies the `tsconfig.json` to add the
`include` configuration for the generated type definitions.
> feat: make tooling extension self-registering 

- packages/cds-plugin-ui5/cds-plugin.js
- packages/cds-plugin-ui5/lib/applyUI5Middleware.js
- packages/cds-plugin-ui5/lib/findUI5Modules.js
- packages/cds-plugin-ui5/package.json
- pnpm-lock.yaml
The current implementation of `CDS_PLUGIN_UI5_LAZY_LOADING` allows for a very fast bootstrapping, but gives no indication to the user, when the loading/mounting of the UI5 applications is actually done.
Because of the asynchronicity, a restart of the cds runtime also breaks the app reload for the UI5 applications, as the apps are not available yet.
If _lazy loading_ is active, all the heavy stuff like graph loading, finding ui5 project dependencies, etc. is moved into the first request, that is being made to the custom router of the specific app module.
As the `Reader` is not yet loaded when lazy mode is active, `glob` is used to determine all relevant `htm[l]` pages. Furthermore it is assumed that the main application folder is called `webapp`.
> fix(cds-plugin-ui5): fixes issue in lazy loading feature
