package.json
packages/ui5-app/package.json
packages/ui5-middleware-cfdestination/package.json
packages/ui5-middleware-livereload/package.json
packages/ui5-middleware-livetranspile/package.json
packages/ui5-middleware-simpleproxy/package.json
packages/ui5-task-transpile/package.json

Fixes: https://github.com/petermuessig/ui5-ecosystem-showcase/issues/20

chore: added author, license and git repo to package.json

---

packages/ui5-middleware-livetranspile/lib/livetranspile.js
packages/ui5-task-transpile/lib/transpile.js

As discussed in Issue #115 I've opened this pull request to fix the issue with mixed line feeds. As this issue is only relevant for deployment I've added the code only in the `transpile` task and not also in `live-transpile` task. 
If you think, I should add it to `live-transpile` task, let me know.

Fix mixed linefeeds

---

packages/ui5-app/package.json
yarn.lock

Revert back UI5 version to 1.73.1 due to bug in >=1.74 with missing resources

---

README.md
docs/index.md

Add ui5-task-minifier module to the task list

docs: Add ui5-task-minifier

---

packages/ui5-middleware-cfdestination/lib/cfdestination.js

It would be even better if I would use `xsenv` first to check whether there is a UAA but this is the hot fix. I hope that works out for you :)

Override security settings to avoid failure or the approuter on start

---

docs/index.md

Added transpiler task including Async Await syntax
Added proxy middleware based on routes

Added a task and middleware

---

README.md

- link ui5-task-babel
- link ui5-middleware-http-proxy
- link ui5-middleware-babel

[CONTRIB] Link task and middlewares

---

packages/ui5-middleware-simpleproxy/lib/proxy.js

Removes the secure flag of cookies when proxying https resources

---

packages/ui5-app/ui5.yaml
packages/ui5-middleware-simpleproxy/lib/proxy.js

Add http headers from environment variable or from the configuration object

Enhance simpleproxy with adding configuration option for http headers

---

packages/ui5-middleware-livereload/lib/livereload.js

Added support to live reload multiple paths, as discussed in email.

ui5-middleware-livereload - watch multiple paths

---

packages/ui5-app/ui5.yaml
packages/ui5-task-transpile/README.md
packages/ui5-task-transpile/lib/transpile.js
packages/ui5-task-transpile/package.json
yarn.lock

Hi,
as discussed in Issue #242 I've provided a pull request based on Lennart's suggestion. Happy to hear your feedback.
Best regards
Lukas

Transpile async/await

---

README.md
docs/index.md
packages/ui5-task-flatten-library/README.md
packages/ui5-task-flatten-library/package.json

chore: Document flatten-library task

---

packages/ui5-middleware-simpleproxy/README.md
packages/ui5-middleware-simpleproxy/lib/proxy.js

Basic authentication popups are annoying, therefore I added basic authentication capability to the proxy. One could use ui5.yaml or ENV vars to set user/password.

feat: Add basic authentication

---

packages/ui5-app/wdio.conf.js
packages/ui5-app/webapp/controller/BaseController.js
packages/ui5-app/webapp/includes/iWillBeTranspiled.js
packages/ui5-app/webapp/test/e2e/binding.spec.js
packages/ui5-app/webapp/test/e2e/conf.js
packages/ui5-app/webapp/test/e2e/interaction.spec.js
packages/ui5-app/webapp/test/e2e/pages/main.view.js
packages/ui5-app/webapp/test/e2e/pages/other.view.js
packages/ui5-app/webapp/test/integration/InteractionJourney.js
packages/ui5-app/webapp/test/integration/pages/Main.js
packages/ui5-app/webapp/test/integration/pages/Other.js

plus some mini streamline refactoring for the tests

chore: kill'em trailing commas!

---

packages/ui5-middleware-livereload/README.md
packages/ui5-middleware-livereload/lib/livereload.js

- multiple exclusions
- single exclusion
can be passed through to liveserver module

feat(livereload): add exclusions option to livereload middleware

---

packages/ui5-task-zipper/lib/zipper.js

fix(zipper): avoid issues when zipping libs with test-resources

---

packages/ui5-middleware-cfdestination/package.json

fixes #446 
ps: @iggycoder anybody can do that, PRs are easy peasy ;)

chore(approuter): bump version

---

docs/index.md

- Added ui5-task-librarian
- Sorted tasks alphabetically

Update index.md with new task and sorted tasks alphabetically

---

packages/ui5-task-compileless/lib/compileLess.js

Hi,
I just checked the app build and it's broken. Luckily the reason was quite obvious ;)

fix(ui5-task-compileless): Fix typo in function parameter

---

.github/workflows/middleware-tests.js.yml
packages/ui5-app/package.json
packages/ui5-middleware-cfdestination/package.json
packages/ui5-task-zipper/.gitignore
packages/ui5-task-zipper/lib/zipper.js
packages/ui5-task-zipper/package.json
packages/ui5-task-zipper/test/__assets__/ui5.additionalFiles.yaml
packages/ui5-task-zipper/test/__assets__/ui5.basic.yaml
packages/ui5-task-zipper/test/__assets__/ui5.customZipName.yaml
packages/ui5-task-zipper/test/__assets__/ui5.includeDeps.yaml
packages/ui5-task-zipper/test/__assets__/ui5.onlyZip.yaml
packages/ui5-task-zipper/test/zipper.test.js
yarn.lock

Hey everyone,
this is a fix for #540. It should replace the first forward slash in call cases. Let me know your thoughts 👍🏾 
I will add the change to the changelog, after you are fine with the change.
Best Regards
Robert

Fix Absolute Path Error for Third Party Dependencies

---

packages/ui5-middleware-stringreplacer/README.md
packages/ui5-task-stringreplacer/README.md

fix(ui5-*-stringreplacer): documentation issues

---

packages/ui5-middleware-onelogin/sample/example_embeddedflp/.env
packages/ui5-middleware-onelogin/sample/example_simpleproxy_and_onelogin/.env

Added URL for environment to sapes5

refactor(component): added env files with url to samples of onelogin

---

packages/ui5-middleware-cfdestination/package.json
packages/ui5-middleware-iasync/package.json
packages/ui5-middleware-index/package.json
packages/ui5-middleware-livecompileless/package.json
packages/ui5-middleware-livereload/package.json
packages/ui5-middleware-livetranspile/package.json
packages/ui5-middleware-onelogin/package.json
packages/ui5-middleware-servestatic/package.json
packages/ui5-middleware-simpleproxy/package.json
packages/ui5-middleware-stringreplacer/package.json
packages/ui5-middleware-webjars/package.json
packages/ui5-task-compileless/package.json
packages/ui5-task-flatten-library/package.json
packages/ui5-task-i18ncheck/package.json
packages/ui5-task-minify-xml/package.json
packages/ui5-task-pwa-enabler/package.json
packages/ui5-task-stringreplacer/package.json
packages/ui5-task-transpile/package.json
packages/ui5-task-zipper/package.json
packages/ui5-tooling-modules/package.json

This reverts commit 0156858ae2b3f9b2d3c54b8bdf94fa45f3972e68 from PR #600
see https://github.com/ui5-community/ui5-community.github.io/issues/84

chore: revert "add metadata to `package.json` for all packages"

---

packages/ui5-task-i18ncheck/lib/utils.js
packages/ui5-task-i18ncheck/package.json
yarn.lock

fix(ui5-task-i18ncheck): update xmldom

---

packages/ui5-app/webapp/view/Main.view.xml
packages/ui5-tooling-modules/lib/task.js

fix(ui5-tooling-modules): avoid stackoverflow for html tags in xmlviews

---

packages/ui5-middleware-stringreplacer/lib/stringreplacer.js
packages/ui5-task-stringreplacer/lib/stringreplacer.js

fix(stringreplacer): respect also the placeholders from ui5.yaml

---

packages/ui5-task-zipper/lib/zipper.js

hi @petermuessig 
as we discussed this is the small change i propose to exclude files from the zip if the OmitFromBuildResult tag is set.

fix: exclude resources with OmitFromBuildResult tag from zip

---

packages/ui5-task-zipper/README.md
packages/ui5-task-zipper/lib/zipper.js
packages/ui5-task-zipper/test/__assets__/ui5.additionalFilesMap.yaml
packages/ui5-task-zipper/test/zipper.test.js

Enhanced task zipper to be able to provide source and target path for `additionalFiles`.

Feat enhance task zipper additionalfiles by target path

---

packages/ui5-task-cachebuster/lib/cachebuster.js

quickfix: need to await promises

fix: ui5-task-cachebuster

---

packages/ui5-middleware-cfdestination/lib/cfdestination.js
packages/ui5-middleware-cfdestination/package.json
packages/ui5-middleware-cfdestination/test/boot.test.js
pnpm-lock.yaml

fix(ui5-middleware-cfdestionation): support h2 devserver mode

---

packages/ui5-task-zipper/lib/zipper.js

The resource collections could be nested, so the project name needs to be derived from one of the nested readers in the collections. With this fix, the project namespace will be searched in the collections recursivly.
Fixes #550

fix(ui5-task-zipper): detection of project name for deps

---

packages/ui5-tooling-modules/lib/util.js

On Windows it can be that the build with ES modules failed since the default
exports of CJS modules aren't detected properly. In this case, the tooling
extension falls back to use CJS modules for bundling first which finally works
to create the bundle. Unfortunately, there is no better solution but so far
this happened only in the context of jspdf in which canvg requires raf and the
default export provided with module.exports isn't detected properly on Windows.
Fixes https://github.com/ui5-community/ui5-ecosystem-showcase/issues/726

fix(ui5-tooling-modules): fallback to cjs modules on Windows

---

package.json
packages/ui5-middleware-simpleproxy/lib/proxy.js

fix(ui5-middleware-proxy): proper error handling for missing baseUri

---

README.md
packages/dev-approuter/README.md
packages/dev-approuter/index.js
packages/dev-approuter/lib/devApprouter.js
packages/dev-approuter/lib/helpers.js
packages/dev-approuter/package.json
pnpm-lock.yaml

Check the [readme](https://github.com/nicoschoenteich/ui5-ecosystem-showcase/blob/main/packages/dev-approuter/README.md) for more info :-)

feat(dev-approuter): initial commit

---

packages/cds-plugin-ui5/README.md
packages/cds-plugin-ui5/cds-plugin.js
packages/cds-plugin-ui5/lib/applyUI5Middleware.js
packages/dev-approuter/lib/devApprouter.js
packages/dev-approuter/lib/helpers.js
showcases/approuter/webapp/index.html
showcases/cds-bookshop/package.json

---
fix(dev-approuter): improved route regexes to avoid conflicts

fix(cds-plugin-ui5): allow relative config files in package.json

---

packages/ui5-middleware-cfdestination/lib/cfdestination.js

fix(ui5-middleware-cfdestination): support x-forwarded-proto with multiple protocols

---

packages/ui5-middleware-cfdestination/README.md
packages/ui5-middleware-cfdestination/lib/cfdestination.js

fix(ui5-middleware-cfdestination): fix x-forwarded-proto multi protocol issue

---

packages/cds-plugin-ui5/package.json
packages/dev-approuter/package.json
packages/karma-ui5-transpile/package.json
packages/ui5-middleware-cap/package.json
packages/ui5-middleware-cfdestination/package.json
packages/ui5-middleware-iasync/package.json
packages/ui5-middleware-index/package.json
packages/ui5-middleware-livecompileless/package.json
packages/ui5-middleware-livereload/package.json
packages/ui5-middleware-onelogin/package.json
packages/ui5-middleware-serveframework/package.json
packages/ui5-middleware-servestatic/package.json
packages/ui5-middleware-simpleproxy/package.json
packages/ui5-middleware-ui5/package.json
packages/ui5-middleware-webjars/package.json
packages/ui5-middleware-websocket/package.json
packages/ui5-task-cachebuster/package.json
packages/ui5-task-compileless/package.json
packages/ui5-task-flatten-library/package.json
packages/ui5-task-i18ncheck/package.json
packages/ui5-task-minify-xml/package.json
packages/ui5-task-pwa-enabler/package.json
packages/ui5-task-zipper/package.json
packages/ui5-tooling-modules/package.json
packages/ui5-tooling-stringreplace/package.json
packages/ui5-tooling-transpile/package.json
packages/ui5-utils-express/package.json

docs: update homepages in package.json

---

packages/ui5-middleware-livecompileless/README.md
packages/ui5-task-compileless/README.md
packages/ui5-task-compileless/lib/compileLess.js
packages/ui5-task-compileless/package.json
pnpm-lock.yaml
showcases/ui5-app/webapp/css/style.css

Reworked the resource handling of the less compiler task to ensure a proper handling of resource paths and to fix issues with incorrect path handling leading to wrong calculation of paths and finally not compiling some less resources.
Fixes #889

fix(ui5-task-compileless): improved resource handling

---

packages/ui5-task-zipper/README.md
packages/ui5-task-zipper/lib/zipper.js
packages/ui5-task-zipper/test/zipper.test.js

Implements #908
documentation contains a "starting with version XXX" wording, which should be adjusted when releasing

feat(ui5-task-zipper): add standalone bundle to zip (#908)

---

packages/ui5-middleware-index/lib/index.js

fix(ui5-middleware-index): re-enable support for URL parameters

---

packages/ui5-middleware-cap/README.md

add missing documentation for existing functionality

docs(ui5-stringreplace-cap): add mountPath

---

packages/ui5-middleware-simpleproxy/lib/proxy.js

fix(ui5-middleware-proxy): handle special case when baseUrl is url

---

packages/ui5-tooling-modules/lib/middleware.js

Normally, modules are detected by scanning the source files. In some cases, due to some circumstances it may be necessary to not expose the source files in the ui5.yaml and then the middleware doesn't find the modules to package. Therefore, the middleware has been extended again to also package modules which are available as NPM package but not found as require or import in the source modules. This finding produces a warning as a hint to check whether the build includes all things properly. For the build (task), this is not issue as it requires the source files anyhow.

fix(ui5-tooling-modules): support for dynamic modules during development

---

packages/ui5-tooling-stringreplace/README.md
packages/ui5-tooling-stringreplace/lib/middleware.js
packages/ui5-tooling-stringreplace/lib/task.js
packages/ui5-tooling-stringreplace/lib/util.js

proposal for - https://github.com/ui5-community/ui5-ecosystem-showcase/issues/948

feat(ui5-stringreplace) - provide configurable separator

---

packages/cds-plugin-ui5/cds-plugin.js
packages/cds-plugin-ui5/lib/findUI5Modules.js

fix(cds-plugin-ui5): only start when using "cds serve|watch"

---

packages/ui5-middleware-ui5/lib/ui5.js

fix(ui5-middleware-ui5): ensure using forward slashes for mount path

---

packages/cds-plugin-ui5/cds-plugin.js

fix(cds-plugin-ui5): start also when services=all is defined

---

packages/ui5-task-pwa-enabler/templates/advancedCache.js

Otherwise, is any unfound files in caching expression:

Improve Error-Handle for not in the cache found files

---

packages/cds-plugin-ui5/lib/findUI5Modules.js
packages/dev-approuter/lib/devApprouter.js
packages/dev-approuter/lib/helpers.js
packages/ui5-middleware-ui5/package.json
pnpm-lock.yaml
showcases/approuter/default-env.json

fix(cds-plugin-ui5): avoid issue when cds is not available
fix(dev-approuter): ensure usage of proper ports for CDS and AppRouter
fix(ui5-middleware-ui5): added dependency to express to allow require

fix: cleanup of dependencies and improved approuter logic

---

packages/ui5-task-pwa-enabler/README.md
packages/ui5-task-pwa-enabler/config.json
packages/ui5-task-pwa-enabler/lib/pwaEnabler.js

This is implementation for feature request #1017 
Resolves: #1017

feat(ui5-task-pwa-enabler): add support for path prefix for file caching

---

packages/ui5-tooling-transpile/lib/task.js

As the default replaceVersion task of the UI5 Tooling only replaces the version for known file extensions and isn't configurable, the custom task ui5-tooling-transpile-task is now also able to replace the version using the central function for all additional file types used in the transpile process.

fix(ui5-tooling-transpile): support replacing versions

---

packages/cds-plugin-ui5/cds-plugin.js

With @sap/cds-dk@8 we now have the possibility to specify the build task priority -1 which runs after the last build task from cds. This can now be used as an official priority to run finally the clean-up.
Fixes #1033

fix(cds-plugin-ui5): support @sap/cds-dk@8 build priorities

---

packages/ui5-tooling-transpile/lib/task.js

fix(ui5-tooling-transpile): ensure consistent line endings

---

packages/cds-plugin-ui5/cds-plugin.js

fix(cds-plugin-ui5): correctly determine the @sap/cds-dk version

---

packages/cds-plugin-ui5/cds-plugin.js

fix(cds-plugin-ui5): fix error when resolving symlinks for CDS-DK root

---

packages/ui5-task-copyright/bin/uses-ui5-task-copyright.js

fix(ui5-task-copyright): detect task being the first entry

---

packages/ui5-tooling-modules/lib/util.js
pnpm-lock.yaml
showcases/ui5-app/local/mypackage/index.js
showcases/ui5-app/local/mypackage/package.json
showcases/ui5-app/package.json
showcases/ui5-app/webapp/controller/Thirdparty.controller.js

fix(ui5-tooling-modules): properly resolve local dependencies

---

showcases/ui5-tsapp-simple/webapp/control/SimpleControl.ts
showcases/ui5-tsapp-webc/webapp/control/HTMLElement.ts

fix(ui5-tsapp-webc): mark HTMLElement renderer as static

fix(ui5-tsapp-simple): mark SimpleControl renderer as static

---

packages/ui5-middleware-serveframework/package.json
pnpm-lock.yaml

Fixes https://github.com/SAP-samples/ui5-typescript-walkthrough/issues/69

fix(ui5-middleware-serveframework): include mandatory dependency to @ui5/builder

---

packages/ui5-task-i18ncheck/lib/utils.js

fix(ui5-task-i18ncheck): fix mime type issue for DOMParser creation

---

packages/ui5-tooling-transpile/lib/task.js

fix(ui5-tooling-transpile): ensure forward slashes for type definitions

---

packages/ui5-tooling-modules/lib/task.js
showcases/ui5-app/webapp/controller/Thirdparty.controller.js

fix(ui5-tooling-modules): ensure rewrites of deps only for require/define APIs

---

packages/ui5-task-zipper/lib/zipper.js

As mentioned in https://github.com/ui5-community/ui5-ecosystem-showcase/pull/1046#issuecomment-2500790525

fix(ui5-task-zipper): also fix relative path in Component-preload.js

---

packages/ui5-tooling-transpile/README.md
packages/ui5-tooling-transpile/lib/util.js
showcases/ui5-tsapp-simple/ui5.yaml

feat(ui5-tooling-transpile): allow to omit source maps generation

---

packages/ui5-task-cachebuster/lib/cachebuster.js

fix(ui5-task-cachebuster): support new resource-roots config option

---

packages/ui5-tooling-modules/README.md
packages/ui5-tooling-modules/lib/rollup-plugin-webcomponents.js
packages/ui5-tooling-modules/test/__snap__/4370bd2f/@ui5/webcomponents/dist/CheckBox.js
packages/ui5-tooling-modules/test/__snap__/56bfa72a/@luigi-project/container/LuigiContainer.js
packages/ui5-tooling-modules/test/__snap__/64fb0379/@ui5/webcomponents/dist/Button.js
packages/ui5-tooling-modules/test/__snap__/d726ec84/@ui5/webcomponents/dist/Panel.js
showcases/ui5-tsapp-webc/ui5.yaml

@Thodd: I deactivated the feature by default as there happened some build issues for colleagues - enabling it by default ones feature works.

fix(ui5-tooling-modules): skip JSDoc generation by default until feature works

---

packages/cds-plugin-ui5/cds-plugin.js

The version check for `@sap/cds-dk` is currently wrong if another script runs like `cds-typer`.
Reproduce with e.g.
```sh
npx -p @cap-js/cds-typer cds-typer "*" 
```
and you get 
```
[cds-plugin-ui5] [WARN] The cds build task requires @sap/cds-dk version >= 7.5.0! Skipping execution as your @sap/cds-dk version is too old...
```
Fix is to check if it's really the `cds` script that runs.

fix: [cds-plugin-ui5] check that it's the `cds` script

---

package.json
packages/cds-plugin-ui5/README.md
packages/cds-plugin-ui5/cds-plugin.js
packages/cds-plugin-ui5/lib/applyUI5Middleware.js
packages/cds-plugin-ui5/lib/createPatchedRouter.js
packages/cds-plugin-ui5/lib/findUI5Modules.js
showcases/cds-bookshop/package.json

This feature introduces lazy loading for UI5 applications and closes the POC of @stockbal (BTW: big thanks for that! nice idea!)
Closes #1193
Fixes #1028

feat(cds-plugin-ui5): add lazy module loading

---

packages/ui5-tooling-modules/lib/task.js
showcases/ui5-tsapp-webc/webapp/controller/Main.controller.ts

fix(ui5-tooling-modules): do not convert dots to slashes for isA rewrite

---

packages/ui5-middleware-approuter/lib/middleware.js
packages/ui5-middleware-approuter/package.json
packages/ui5-middleware-simpleproxy/lib/proxy.js
packages/ui5-middleware-simpleproxy/package.json
packages/ui5-middleware-simpleproxy/test/proxy.test.js
pnpm-lock.yaml

feat(ui5-middleware-simpleproxy): upgrade to http-proxy-middleware@3.0.5
Fixes #1263

feat(ui5-middleware-approuter): upgrade to http-proxy-middleware@3.0.5
